### ISSUE TITLE
torchtyping requires typeguard version <3.0

### ISSUE THREAD

**Issue by jumelet** [inseq-team/inseq#176]
## 🐛 Bug Report

In the requirements.txt it is stated that `typeguard==3.0.1`, but `torchtyping` is incompatible with typeguard versions >3.0 (https://github.com/patrick-kidger/torchtyping#installation).

For me this led to issues with importing inseq, raising the following import error:
```python
ImportError: cannot import name 'LiteralString' from 'typing_extensions'
```

However, it turned out the issue there did not stem from the `typing_extensions` library, but the `typeguard` version: once I had set that to version `2.13.3` the error disappeared.

**Comment by gsarti** [comment]
Thanks @jumelet! Could you indicate the Python version you're using so that I can try to reproduce the bug? Interesting because I would expect CI tests to fail if this was an issue with supported versions (Py >= 3.8.1, < 3.12).

As a side note, on the long term we should switch to `jaxtyping` (#167 ) which should be maintained and less problematic!

**Comment by gsarti** [comment]
Tested with same versions on Python `3.9.13` under both conda and regular venv and a simple attribution with Inseq works both with `typeguard==2.13.3` and `3.0.1`. Still, `typeguard` will be pinned to `<3´ as precautionary measure for the next release, waiting for `jaxtyping` integration.

**Comment by carschno** [comment]
Unfortunately, switching to jaxtyping (#226) does not resolve this issue, because jaxtyping also requires typeguard<3 ([source](https://github.com/google/jaxtyping/blob/9646eff7e1926e757a11906b03c53beb42f5ad48/pyproject.toml#L26)).
