### ISSUE TITLE
Which aggregation function is better?

### ISSUE THREAD

**Issue by MarshtompCS** [inseq-team/inseq#261]
## Question

The default aggregation function is "vnorm", but there are several choices for aggregation. 

I wonder if there is a best aggregation function selection choice for each attribution method.

> inseq.list_aggregation_functions()
> ['sum', 'max', 'min', 'mean', 'vnorm', 'absmax', 'prod']

## Checklist

- [x] I've searched the project's [`issues`](https://github.com/inseq-team/inseq/issues?q=is%3Aissue).

**Comment by gsarti** [comment]
Hi @MarshtompCS,

The general answer to this is that there is no free lunch, and hence no one-size-fit-all aggregation method that outperforms all others regardless of the choice of model and task. I suggest trying out different options and see what works best in your use-case.

I believe that the L2 norm (`vnorm` with `vnorm_ord=2`) is a sensible default for gradient-based methods because it can capture a notion of contribution magnitude (without sign), allowing for renormalization (applied by default, use `normalize=False` in `out.aggregate` or `out.show` to remove it) to obtain relative saliency of every input. If you have other ideas I'd be happy to hear them!
