### ISSUE TITLE
Issue with zeroing_value attribution and SubwordAggregator()

### ISSUE THREAD

**Issue by rafikg** [inseq-team/inseq#291]
## Question

This is MRE:

```
import inseq
from transformers import M2M100ForConditionalGeneration, M2M100Tokenizer
from inseq.data.aggregator import  SubwordAggregator
import torch
import numpy as np
model = M2M100ForConditionalGeneration.from_pretrained("facebook/m2m100_418M")
tokenizer = M2M100Tokenizer.from_pretrained("facebook/m2m100_418M")
tokenizer.src_lang = 'en'
tokenizer.tgt_lang = 'fr'
model = inseq.load_model(model=model,
                         tokenizer=tokenizer,
                         attribution_method="value_zeroing")
s = time.time()
out = model.attribute(
    input_texts="Life is like a box of chocolates.",
    generated_texts="La vie est comme une boite de chocolats.",
    attribute_target=False,
    show_progress=True,
)
f = time.time()
# out.show() # this is working
agg = SubwordAggregator()
agg_out = agg.aggregate(attr=out[0].sequence_attributions)
agg_out.show(do_aggregation=True) ## Here is the error

```
**Error:**
<img width="696" alt="image" src="https://github.com/user-attachments/assets/0f47c3fe-2069-4b68-a8e2-044969ce8559">

**`value_zeroing`:**  source_length X target_length X n_heads
<img width="826" alt="image" src="https://github.com/user-attachments/assets/f6b4a2af-a328-4ccc-b0ba-13006d6f1114">
**`Attention`**
<img width="899" alt="image" src="https://github.com/user-attachments/assets/5b98996d-a09c-4d6f-a129-c40c91978522">

- [x] I've searched the project's [`issues`](https://github.com/inseq-team/inseq/issues?q=is%3Aissue).

**Comment by gsarti** [comment]
Hi @rafikg, thank you for reporting this, good catch! I just opened a PR #292 that should fix this issue with the aggregation step, could you verify if it is working for you now?

**Comment by rafikg** [comment]
@gsarti Thanks it is working on my side.

**Comment by gsarti** [comment]
Hi @rafikg,

Attribution methods cannot be used to obtain an absolute notion of "importance" per generated token, since as you mention, scores reflect relative contributions of source tokens towards the generation of specific target tokens. At best, what you can do is to analyze whether some properties of the attribution scores distribution are informative (e.g. the entropy of attributions in error spans vs. regular tokens). You can find similar analyses e.g. by [Voita et al. 2021](https://aclanthology.org/2021.acl-long.91/), [Dale et al. 2023](https://arxiv.org/abs/2212.08597) and [Ferrando et al. 2022](https://aclanthology.org/2022.emnlp-main.599/), among others.

Another alternative you might be interested into is to inspect some of the [`step_scores`](https://inseq.org/en/latest/main_classes/step_functions.html#pre-registered-step-functions) that can be extracted for every generation step with Inseq. For example, `entropy` or `top_p_size` can provide useful information on the peakedness of the vocabulary distribution at every generation step. If you have post-edited versions of the same text, you can inspect how their attributions differ by auto-aligning their contents (see section "Providing custom alignments for contrastive targets" in the [Inseq tutorial](https://github.com/inseq-team/inseq/blob/main/examples/inseq_tutorial.ipynb)).

Hope this helps!

**Comment by rafikg** [comment]
Thanks @gsarti. This  paper does exactly what I am looking for.

**Comment by rafikg** [comment]
hi @gsarti,
I tried your suggestion to use entropy. Something like this:
```
out = model.attribute(
    input_texts="Life is like a box of chocolates.",
    generated_texts="La vie est comme une boite de chocolats.",
    generation_args={"forced_bos_token_id": tokenizer.get_lang_id("fr")},
    attribute_target=False,
    show_progress=True,
    skip_special_tokens=True,
    step_scores=['entropy'],
    n_steps=300
```
My understanding is for each step =1, n_steps and for each token, we calculate its entropy. So, after 300 steps, we got a matrix of [number_of_target_tokens*300]. Did you sum across steps ? If my understanding is correct, is there a way to the original matrix ?

<img width="732" alt="image" src="https://github.com/user-attachments/assets/d99bfe01-0538-42ec-9ffd-25512968ac28">

**Comment by gsarti** [comment]
Hi @rafikg,

In the matrix you show, entropy scores are only represented by the bottom row, i.e. one value (the entropy of the predictive distribution) per generated token. After 300 steps, this would be a tensor of 300 scores. The other scores you see in the matrix are attribution scores computed with `saliency` by default, but you are not using them. You can specify `method="dummy"` in `model.attribute` to avoid the attribution and only compute step scores like entropy.

**Comment by rafikg** [comment]
Sorry for the misunderstanding, I know that the entropy is only the last row and the rest are the attribution scores. My question is more about if the entropy is calculated in each step (1->n_steps) and then aggregated by summation or it is calculate one time ?
Why I am asking this question, because in my code the `out` variable step_scores before the aggregation is not a tensor of 300*number_of_target_token. it is a vector of  number_of_target_token. Thanks

**Comment by gsarti** [comment]
Ah I see, you're asking how entropy scores are aggregated when aggregation is applied to the output, right? You can see from here that the default aggregation operation for the `entropy` step function is `sum`: https://github.com/inseq-team/inseq/blob/1078e1917834f00139dd369e7eb3e48abfed795c/inseq/data/aggregation_functions.py#L95. So yes, entropy scores are summed across subwords when these are aggregated with `ContiguousSpansAggregator` or `SubwordsAggregator`. The length of the corresponding vector is always equal to the number of generated tokens, where every score represents the entropy of the predictive distribution at every generation step.
